name: 'Changelog Validator'
icon: check-circle
color: green
description: 'Validates that CHANGELOG.md exists and follows the expected format'
inputs:
  changelog-path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.md'
  check-updated:
    description: 'Check if changelog was updated in PR'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.changelog-path }}
    - ${{ inputs.check-updated }}