name: Validate Changelog

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Changelog
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Validate Changelog
        uses: ./
        with:
          changelog-path: 'test/CHANGELOG.md'
          check-updated: 'true'